// Gemini prompts — ported exactly from the Python photo_sorter.py

const TRIP_NAME_PROMPT = `Name photo trip folders for {year}.

Rules:
- If the trip covers multiple distinct cities (especially across different countries), list the main cities joined by " & " — e.g. "Nizza & Monaco", "Prague & Vienna"
- If the trip spans many cities spread across a whole country (a true country-wide road trip), the country name is fine — e.g. "Portugal", "Japan".
- If the trip is concentrated in one city or a specific region, use that city or region instead — e.g. "Bavaria", "French Alps", "Hamburg".
- If the locations list contains district or county names (e.g. "Mühlviertel") instead of city names, infer the nearest well-known city or region from context rather than using the district name.
- Single-city trips: just the city name — e.g. "Hamburg", "Rome"
- NO generic suffixes (no Trip/Visit/Vacation/Journey/Tour/Holiday)
- Max 4 words total

Trips (id: date_range, n_photos, locations, [tags]):
{trips_compact}

JSON only: {"trips":[{"id":0,"folder_name":"Porto"}]}`;

const HOME_EVENTS_PROMPT = `Identify special events from home/unknown photo sessions in {year}.

The tags per session were generated by an image classifier and are hints only — they can be wrong or noisy. Base your decision primarily on the combination of photo count, date pattern, and how strongly/consistently the tags point to the same event type.

EVENT=yes: any clearly identifiable special occasion — e.g. a wedding, concert, birthday party, sports event, graduation, family gathering, or similar notable event. Typically: a burst of many photos on the same day or consecutive days with consistent tags.
EVENT=no: everyday photos — casual selfies, pet photos, random food shots, shopping, errands, or a scattered mix of unrelated tags.

Rules:
- Content tags are generated by an image classifier and are HINTS ONLY — they are frequently wrong. Never name an event solely because of one or two matching tags.
- "Wedding": only if ≥10 photos AND ≥2 photos independently tagged "wedding". Otherwise use "Party" or mark flat.
- "Concert": only if ≥3 photos independently tagged "concert or live show". Otherwise use "Night Out" or "Show".
- When uncertain between a specific name and a generic one, ALWAYS prefer the generic one.
- You may group multiple consecutive sessions into one event if they clearly belong together.
- Each session ID may only appear in one event — never assign the same session_id to two events.
- When unsure whether something is an event at all, mark it as flat.

Sessions (id,date,n_photos,tags):
{sessions_compact}

JSON only: {"events":[{"session_ids":[0,1],"folder_name":"Summer Party"}],"flat_session_ids":[2,3]}
Folder names: short, descriptive, based on the actual content (e.g. "Beach Day", "Family Dinner", "Night Out", "Football Game"). No location. Unsure=flat.`;

module.exports = { TRIP_NAME_PROMPT, HOME_EVENTS_PROMPT };
