// Gemini prompts — ported exactly from the Python photo_sorter.py

const TRIP_NAME_PROMPT = `Name photo trip folders for {year}.

Rules:
- 1-3 words; use the most prominent city or region name
- If multiple cities in one country, use the country or the most-visited city
- NO generic suffixes (no Trip/Visit/Vacation/Journey/Tour/Holiday)
- Examples: "Portugal", "Hamburg", "Rome", "French Alps", "Lisbon"

Trips (id: date_range, n_photos, locations, [tags]):
{trips_compact}

JSON only: {"trips":[{"id":0,"folder_name":"Porto"}]}`;

const HOME_EVENTS_PROMPT = `Identify special events from home/unknown photo sessions in {year}.

The tags per session were generated by an image classifier and are hints only — they can be wrong or noisy. Base your decision primarily on the combination of photo count, date pattern, and how strongly/consistently the tags point to the same event type.

EVENT=yes: any clearly identifiable special occasion — e.g. a wedding, concert, birthday party, sports event, graduation, family gathering, or similar notable event. Typically: a burst of many photos on the same day or consecutive days with consistent tags.
EVENT=no: everyday photos — casual selfies, pet photos, random food shots, shopping, errands, or a scattered mix of unrelated tags.

Rules:
- Only assign a specific event name (e.g. "Wedding") if the tags are strong and consistent across multiple photos. A single weak tag is not enough.
- When uncertain between a specific name and a generic one, use the generic one (e.g. "Party" instead of "Wedding", "Show" instead of "Concert").
- You may group multiple consecutive sessions into one event if they clearly belong together.
- The example folder names below are just illustrations — invent whatever name best describes what actually happened.
- When unsure whether something is an event at all, mark it as flat.

Sessions (id,date,n_photos,tags):
{sessions_compact}

JSON only: {"events":[{"session_ids":[0,1],"folder_name":"Summer Party"}],"flat_session_ids":[2,3]}
Folder names: short, descriptive, based on the actual content (e.g. "Beach Day", "Family Dinner", "Night Out", "Football Game"). No location. Unsure=flat.`;

module.exports = { TRIP_NAME_PROMPT, HOME_EVENTS_PROMPT };
